/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import javax.swing.JTextField;

public class PanelDatosPrestamos extends javax.swing.JPanel {

    /**
     * Creates new form PanelDatos
     */
    public PanelDatosPrestamos() {
        initComponents();
    }

    public JTextField getjTextFieldDias() {
        return jTextFieldDias;
    }

    public JTextField getjTextFieldEstado() {
        return jTextFieldEstado;
    }

    public JTextField getjTextFieldFDevolucion() {
        return jTextFieldFDevolucion;
    }

    public JTextField getjTextFieldFDevolucionU() {
        return jTextFieldFDevolucionU;
    }

    public JTextField getjTextFieldFPrestamo() {
        return jTextFieldFPrestamo;
    }

    public JTextField getjTextFieldProducto() {
        return jTextFieldProducto;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldProducto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldFPrestamo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldEstado = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldFDevolucion = new javax.swing.JTextField();
        jTextFieldFDevolucionU = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldDias = new javax.swing.JTextField();

        setLayout(null);

        jLabel1.setText("Producto");
        add(jLabel1);
        jLabel1.setBounds(0, 4, 550, 33);

        jTextFieldProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldProductoActionPerformed(evt);
            }
        });
        add(jTextFieldProducto);
        jTextFieldProducto.setBounds(0, 37, 550, 33);

        jLabel2.setText("Fecha Prestamo");
        add(jLabel2);
        jLabel2.setBounds(0, 70, 550, 33);
        add(jTextFieldFPrestamo);
        jTextFieldFPrestamo.setBounds(0, 103, 550, 33);

        jLabel3.setText("Fecha Devolucion Determinada");
        add(jLabel3);
        jLabel3.setBounds(0, 136, 550, 33);

        jLabel4.setText("Fecha devolución Usuario");
        add(jLabel4);
        jLabel4.setBounds(0, 202, 550, 33);
        add(jTextFieldEstado);
        jTextFieldEstado.setBounds(0, 360, 550, 33);

        jLabel5.setText("Estado");
        add(jLabel5);
        jLabel5.setBounds(0, 330, 550, 33);

        jTextFieldFDevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFDevolucionActionPerformed(evt);
            }
        });
        add(jTextFieldFDevolucion);
        jTextFieldFDevolucion.setBounds(0, 170, 550, 30);
        add(jTextFieldFDevolucionU);
        jTextFieldFDevolucionU.setBounds(0, 235, 550, 33);

        jLabel6.setText("Días/Horas permitidos");
        add(jLabel6);
        jLabel6.setBounds(0, 268, 550, 33);
        add(jTextFieldDias);
        jTextFieldDias.setBounds(0, 300, 550, 33);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProductoActionPerformed

    private void jTextFieldFDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFDevolucionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFDevolucionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextFieldDias;
    private javax.swing.JTextField jTextFieldEstado;
    private javax.swing.JTextField jTextFieldFDevolucion;
    private javax.swing.JTextField jTextFieldFDevolucionU;
    private javax.swing.JTextField jTextFieldFPrestamo;
    private javax.swing.JTextField jTextFieldProducto;
    // End of variables declaration//GEN-END:variables
}
