/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import AdapterTemplateMethod_SingletonProxyServidor.AdaptadorServidor;
import AdapterTemplateMethod_SingletonProxyServidor.AdaptadorServidorProductoBiblioteca;
import FactPublicaciones.FactoriaPublicaciones;
import FactPublicaciones.Publicacion;
import bibliotecacafeteria.Biblioteca;
import PersonalUniversidad.PersonalUniversidad;
import SingletonProxyServidor.SingletonProxyServidor;
import SingletonProxyServidor.TipoArchivo;
import java.awt.Color;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Álvaro Zamorano
 */
public class VentanaAltaPublicacion extends javax.swing.JFrame {

    private VentanaBibliotecario padre;

    private PersonalUniversidad usuario;

    private AdaptadorServidor adaptadorServidorPublicacion;

    private HashMap mapProductosBiblioteca;

    private FactoriaPublicaciones factoria;

    /**
     * Creates new form VentanaAltaProductoBiblioteca
     */
    public VentanaAltaPublicacion(VentanaBibliotecario ventana, PersonalUniversidad usuario) {
        padre = ventana;
        padre.setVisible(false);
        this.setVisible(true);
        initComponents();
        this.getContentPane().setBackground(Color.orange);
        this.usuario = usuario;
        adaptadorServidorPublicacion = new AdaptadorServidorProductoBiblioteca();
        mapProductosBiblioteca = adaptadorServidorPublicacion.obtener_todo_dato();
        factoria = new FactoriaPublicaciones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldISBN = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldTitulo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldParam1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldFecha = new javax.swing.JTextField();
        jLabelParam3 = new javax.swing.JLabel();
        jTextFieldAutor = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelParam1 = new javax.swing.JLabel();
        jLabelParam2 = new javax.swing.JLabel();
        jTextFieldMateria = new javax.swing.JTextField();
        jTextFieldParam2 = new javax.swing.JTextField();
        jTextFieldParam3 = new javax.swing.JTextField();
        jButtonAlta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SISTEMA CAFETERIA Y BIBLIOTECA");
        setMinimumSize(new java.awt.Dimension(550, 450));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 14)); // NOI18N
        jLabel1.setText("Seleccione Tipo:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(260, 20, 100, 16);
        getContentPane().add(jTextFieldID);
        jTextFieldID.setBounds(112, 6, 100, 30);

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 14)); // NOI18N
        jLabel2.setText("ISBN:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 60, 31, 16);
        getContentPane().add(jTextFieldISBN);
        jTextFieldISBN.setBounds(110, 50, 100, 30);

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 14)); // NOI18N
        jLabel3.setText("Título:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 110, 33, 16);
        getContentPane().add(jTextFieldTitulo);
        jTextFieldTitulo.setBounds(110, 100, 100, 30);

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 14)); // NOI18N
        jLabel4.setText("Autor:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(21, 155, 33, 16);
        getContentPane().add(jTextFieldParam1);
        jTextFieldParam1.setBounds(170, 280, 110, 30);

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 14)); // NOI18N
        jLabel5.setText("Fecha de publicación:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(21, 202, 118, 16);
        getContentPane().add(jTextFieldFecha);
        jTextFieldFecha.setBounds(170, 190, 150, 30);

        jLabelParam3.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 14)); // NOI18N
        jLabelParam3.setText("Edición:");
        getContentPane().add(jLabelParam3);
        jLabelParam3.setBounds(20, 370, 90, 16);
        getContentPane().add(jTextFieldAutor);
        jTextFieldAutor.setBounds(170, 140, 110, 30);

        jComboBox1.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Libro", "Revista", "Proyecto" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(376, 20, 90, 20);

        jLabel7.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 14)); // NOI18N
        jLabel7.setText("Identificador:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(21, 17, 73, 16);

        jLabel8.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 14)); // NOI18N
        jLabel8.setText("Materia:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(21, 246, 46, 16);

        jLabelParam1.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 14)); // NOI18N
        jLabelParam1.setText("Editorial:");
        getContentPane().add(jLabelParam1);
        jLabelParam1.setBounds(20, 290, 140, 16);

        jLabelParam2.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 14)); // NOI18N
        jLabelParam2.setText("Localidad de publicación:");
        getContentPane().add(jLabelParam2);
        jLabelParam2.setBounds(20, 330, 160, 16);
        getContentPane().add(jTextFieldMateria);
        jTextFieldMateria.setBounds(170, 230, 110, 30);
        getContentPane().add(jTextFieldParam2);
        jTextFieldParam2.setBounds(240, 320, 120, 30);
        getContentPane().add(jTextFieldParam3);
        jTextFieldParam3.setBounds(170, 360, 120, 30);

        jButtonAlta.setBackground(new java.awt.Color(0, 0, 0));
        jButtonAlta.setForeground(new java.awt.Color(255, 255, 0));
        jButtonAlta.setText("Añadir");
        jButtonAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAlta);
        jButtonAlta.setBounds(376, 73, 90, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        padre.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    /**
     * Cambia la variable global seleccion dependiendo de la opción elegida en
     * el jComboBox
     *
     * @param evt
     */
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        int seleccion = jComboBox1.getSelectedIndex();
        switch (seleccion) {
            case 0:
                //Cambiar layout a libro               
                jLabelParam1.setText("Editorial:");
                jLabelParam2.setText("Contenido:");
                jLabelParam3.setText("Edición:");
                break;
            case 1:
                //Cambiar a revista
                jLabelParam1.setText("Periodicidad:");
                jLabelParam2.setText("Volumen:");
                jLabelParam3.setText("NºPublicación:");
                break;
            default:
                //Cambiar a proyecto
                jLabelParam1.setText("Tribunal:");
                jLabelParam2.setText("Departamento:");
                jLabelParam3.setText("Calificación:");
                break;
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * Da de alta una nueva publicación
     * @param evt 
     */
    private void jButtonAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltaActionPerformed

        if (mapProductosBiblioteca.containsKey(jTextFieldID.getText())) {
            JOptionPane.showMessageDialog(this, "ERROR: La publicacion ya se encuentra registrada");
        } else if ((jTextFieldID.getText().isEmpty()) || (jTextFieldAutor.getText().isEmpty())
                || (jTextFieldFecha.getText().isEmpty()) || (jTextFieldISBN.getText().isEmpty())
                || (jTextFieldMateria.getText().isEmpty()) || (jTextFieldTitulo.getText().isEmpty())
                || (jTextFieldParam1.getText().isEmpty()) || (jTextFieldParam2.getText().isEmpty())
                || (jTextFieldParam3.getText().isEmpty())) {
            JOptionPane.showMessageDialog(this, "ERROR: Debe rellenar todos los campos");
        } else {
            try {
                int seleccion = jComboBox1.getSelectedIndex();
                Publicacion publicacion;
                String fechaString = jTextFieldFecha.getText();
                SimpleDateFormat f1 = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
                Date dateFecha = f1.parse(fechaString);
                String biblio = usuario.getRolBibliotecario().getBiblioteca();
                Biblioteca biblioteca = (Biblioteca) SingletonProxyServidor.getInstancia().cargar_archivo(TipoArchivo.BIBLIOTECA, biblio);
                switch (seleccion) {
                    case 0:
                        //libro
                        String param3L = jTextFieldParam3.getText();
                        int par3L = Integer.parseInt(param3L);
                        publicacion = factoria.getPublicacion(seleccion, jTextFieldParam1.getText(), jTextFieldParam2.getText(),
                                par3L, jTextFieldID.getText(), jTextFieldISBN.getText(),
                                jTextFieldTitulo.getText(), jTextFieldAutor.getText(), dateFecha,
                                jTextFieldMateria.getText(), biblioteca);
                        break;
                    case 1:
                        //revista
                        String param2R = jTextFieldParam2.getText();
                        int par2R = Integer.parseInt(param2R);
                        String param3R = jTextFieldParam3.getText();
                        int par3R = Integer.parseInt(param3R);
                        publicacion = factoria.getPublicacion(seleccion, jTextFieldParam1.getText(), par2R,
                                par3R, jTextFieldID.getText(), jTextFieldISBN.getText(),
                                jTextFieldTitulo.getText(), jTextFieldAutor.getText(), dateFecha,
                                jTextFieldMateria.getText(), biblioteca);
                        break;
                    default:
                        //proyecto
                        String param1P = jTextFieldParam1.getText();
                        String[] arrOfStr = param1P.split(",");
                        ArrayList<String> tribunal = new ArrayList<>();
                        for (String a : arrOfStr) {
                            tribunal.add(a);
                        }
                        String param3P = jTextFieldParam3.getText();
                        double par3P = Double.parseDouble(param3P);
                        publicacion = factoria.getPublicacion(seleccion, tribunal, jTextFieldParam2.getText(),
                                par3P, jTextFieldID.getText(), jTextFieldISBN.getText(),
                                jTextFieldTitulo.getText(), jTextFieldAutor.getText(), dateFecha,
                                jTextFieldMateria.getText(), biblioteca);
                        break;
                }

                JOptionPane.showMessageDialog(this, "Publicacion " + jTextFieldID.getText() + " registrada correctamente");
                SingletonProxyServidor.getInstancia().guardar_archivo(usuario);
                SingletonProxyServidor.getInstancia().guardar_archivo(publicacion);
                SingletonProxyServidor.getInstancia().guardar_archivo(biblioteca);
                mapProductosBiblioteca = adaptadorServidorPublicacion.obtener_todo_dato();
            } catch (ParseException ex) {
                Logger.getLogger(VentanaAltaPublicacion.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(VentanaAltaPublicacion.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(VentanaAltaPublicacion.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonAltaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlta;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelParam1;
    private javax.swing.JLabel jLabelParam2;
    private javax.swing.JLabel jLabelParam3;
    private javax.swing.JTextField jTextFieldAutor;
    private javax.swing.JTextField jTextFieldFecha;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldISBN;
    private javax.swing.JTextField jTextFieldMateria;
    private javax.swing.JTextField jTextFieldParam1;
    private javax.swing.JTextField jTextFieldParam2;
    private javax.swing.JTextField jTextFieldParam3;
    private javax.swing.JTextField jTextFieldTitulo;
    // End of variables declaration//GEN-END:variables
}
