package ventanas;

import bibliotecacafeteria.Biblioteca;
import bibliotecacafeteria.Cafeteria;
import PersonalUniversidad.PersonalUniversidad;
import SingletonProxyServidor.SingletonProxyServidor;
import SingletonProxyServidor.TipoArchivo;
import StateComanda.Comanda;
import java.awt.Color;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


public class VentanaCocinarComanda extends javax.swing.JFrame {

    private VentanaCamarero padre;

    private PersonalUniversidad usuario;

    private Biblioteca biblioteca;

    /**
     * Creates new form VentanaConcederPrestamo
     */
    public VentanaCocinarComanda(VentanaCamarero ventana, PersonalUniversidad usuario) throws IOException, ClassNotFoundException {
        padre = ventana;
        padre.setVisible(false);
        this.setVisible(true);
        initComponents();
        this.getContentPane().setBackground(Color.orange);
        this.usuario = usuario;
        actualizarListaComandas();
    }
    
    private void actualizarListaComandas() throws IOException, ClassNotFoundException{
        String nombre_cafeteria = usuario.getRolCamarero().getNombre_cafeteria();
        Cafeteria cafeteria = (Cafeteria) SingletonProxyServidor.getInstancia().cargar_archivo(TipoArchivo.CAFETERIA, nombre_cafeteria);
        jTextAreaPrestamos.setText(cafeteria.obtenerComandasPendientesString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonCocinar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaPrestamos = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SISTEMA CAFETERIA Y BIBLIOTECA");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jLabel1.setText("Introduce id de Comanda a conceder:");

        jButtonCocinar.setBackground(new java.awt.Color(0, 0, 0));
        jButtonCocinar.setForeground(new java.awt.Color(255, 255, 0));
        jButtonCocinar.setText("Cocinar");
        jButtonCocinar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCocinarActionPerformed(evt);
            }
        });

        jTextAreaPrestamos.setColumns(20);
        jTextAreaPrestamos.setRows(5);
        jScrollPane1.setViewportView(jTextAreaPrestamos);

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 14)); // NOI18N
        jLabel2.setText("Comandas a cocinar:");

        jTextFieldId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(47, 47, 47)
                        .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addComponent(jButtonCocinar)
                        .addGap(29, 29, 29))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButtonCocinar)
                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        padre.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void jButtonCocinarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCocinarActionPerformed
        try {
            Integer index = Integer.valueOf(jTextFieldId.getText())-1;
            String nombre_cafeteria = usuario.getRolCamarero().getNombre_cafeteria();
            Cafeteria cafeteria = (Cafeteria) SingletonProxyServidor.getInstancia().cargar_archivo(TipoArchivo.CAFETERIA, nombre_cafeteria);
            
            ArrayList<Comanda> listaComandasPendientes = cafeteria.obtenerComandasPendientes();
            
            listaComandasPendientes.get(index).prepararComanda();
            listaComandasPendientes.get(index).entregarComanda();
            JOptionPane.showMessageDialog(this,"\n¡Comanda cocinada y entregada! " ,"Fallo",JOptionPane.INFORMATION_MESSAGE);     
            SingletonProxyServidor singletonProxyServidor = SingletonProxyServidor.getInstancia();
                try {
                    //Guardar la nueva Cafeteria en su carpeta.
                    singletonProxyServidor.guardar_archivo(cafeteria);
                } catch (IOException ex) {
                    Logger.getLogger(VentanaAltaProductoCafeteria.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            actualizarListaComandas();
        
        } catch (IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this,"\nNo existe dicha comanda " ,"Fallo",JOptionPane.ERROR_MESSAGE);            
        }


    }//GEN-LAST:event_jButtonCocinarActionPerformed

    private void jTextFieldIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCocinar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaPrestamos;
    private javax.swing.JTextField jTextFieldId;
    // End of variables declaration//GEN-END:variables
}
