/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import PersonalUniversidad.PersonalUniversidad;
import bibliotecacafeteria.UsuarioException;
import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Álvaro Zamorano
 */
public class VentanaUsuario extends javax.swing.JFrame {

    /**
     * Creates new form VentanaUsuario
     */
    private VentanaPrincipal padre;

    private PersonalUniversidad usuario;

    public VentanaUsuario(VentanaPrincipal ventana, PersonalUniversidad usuario) {
        padre = ventana;
        padre.setVisible(false);
        this.setVisible(true);
        initComponents();
        this.getContentPane().setBackground(Color.orange);
        this.usuario = usuario;
        jLabelNombre.setText(usuario.getNombre());
        jLabelApellidos.setText(usuario.getApellidos());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelPrestamos = new javax.swing.JLabel();
        jLabelCafeteria = new javax.swing.JLabel();
        jLabelBibliotecario = new javax.swing.JLabel();
        jLabelCamarero = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelApellidos = new javax.swing.JLabel();
        jButtonBiblioteca = new javax.swing.JButton();
        jButtonCafeteria = new javax.swing.JButton();
        jButtonBibliotecario = new javax.swing.JButton();
        jButtonCamarero = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SISTEMA CAFETERIA Y BIBLIOTECA");
        setBackground(new java.awt.Color(153, 255, 255));
        setPreferredSize(new java.awt.Dimension(549, 450));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setText("Nombre:");

        jLabel2.setText("Apellidos:");

        jLabelPrestamos.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 24)); // NOI18N
        jLabelPrestamos.setText("Biblioteca:");

        jLabelCafeteria.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 24)); // NOI18N
        jLabelCafeteria.setText("Cafetería:");

        jLabelBibliotecario.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 24)); // NOI18N
        jLabelBibliotecario.setText("Bibliotecario:");

        jLabelCamarero.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 24)); // NOI18N
        jLabelCamarero.setText("Camarero:");

        jLabelNombre.setText("Nombre");

        jLabelApellidos.setText("Apellidos");

        jButtonBiblioteca.setBackground(new java.awt.Color(0, 0, 0));
        jButtonBiblioteca.setForeground(new java.awt.Color(255, 255, 0));
        jButtonBiblioteca.setText("Acceder");
        jButtonBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBibliotecaActionPerformed(evt);
            }
        });

        jButtonCafeteria.setBackground(new java.awt.Color(0, 0, 0));
        jButtonCafeteria.setForeground(new java.awt.Color(255, 255, 0));
        jButtonCafeteria.setText("Acceder");
        jButtonCafeteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCafeteriaActionPerformed(evt);
            }
        });

        jButtonBibliotecario.setBackground(new java.awt.Color(0, 0, 0));
        jButtonBibliotecario.setForeground(new java.awt.Color(255, 255, 0));
        jButtonBibliotecario.setText("Acceder");
        jButtonBibliotecario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBibliotecarioActionPerformed(evt);
            }
        });

        jButtonCamarero.setBackground(new java.awt.Color(0, 0, 0));
        jButtonCamarero.setForeground(new java.awt.Color(255, 255, 0));
        jButtonCamarero.setText("Acceder");
        jButtonCamarero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCamareroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPrestamos)
                    .addComponent(jLabelCafeteria)
                    .addComponent(jLabelBibliotecario)
                    .addComponent(jLabelCamarero))
                .addContainerGap(294, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonCafeteria, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonBibliotecario, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCamarero, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelApellidos))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrestamos)
                    .addComponent(jButtonBiblioteca))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCafeteria)
                    .addComponent(jLabelCafeteria))
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBibliotecario)
                    .addComponent(jButtonBibliotecario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCamarero)
                    .addComponent(jButtonCamarero))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        padre.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    /**
     * Se muestra la ventana de realizar una acción en la biblioteca
     *
     * @param evt
     */
    private void jButtonBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBibliotecaActionPerformed
        try {
            VentanaPrestamos vp = new VentanaPrestamos(this, usuario);
        } catch (IOException ex) {
            Logger.getLogger(VentanaUsuario.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VentanaUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonBibliotecaActionPerformed

    /**
     * Se muestra la ventana de realizar una comanda en la cafeteria
     *
     * @param evt
     */
    private void jButtonCafeteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCafeteriaActionPerformed
        try {
            VentanaCafeteria vp = new VentanaCafeteria(this, usuario);
        } catch (IOException ex) {
            Logger.getLogger(VentanaUsuario.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VentanaUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonCafeteriaActionPerformed

    /**
     * Se muestra la ventana de las acciones permitidas por el bibliotecario
     *
     * @param evt
     */
    private void jButtonBibliotecarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBibliotecarioActionPerformed
        try {
            if (usuario.esBibliotecario()) {
                VentanaBibliotecario vp = new VentanaBibliotecario(this, usuario);
            } else {
                throw new UsuarioException(UsuarioException.SIN_PERMISOS);
            }
        } catch (UsuarioException nm) {
            JOptionPane.showMessageDialog(this, nm.getMessage(), "Mensaje", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString(), "Mensaje", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_jButtonBibliotecarioActionPerformed

    /**
     * Se muestra la ventana de las acciones permitidas por el camarero
     *
     * @param evt
     */
    private void jButtonCamareroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCamareroActionPerformed
        try {
            if (usuario.esCamarero()) {
                VentanaCamarero vp = new VentanaCamarero(this, usuario);
            } else {
                throw new UsuarioException(UsuarioException.SIN_PERMISOS);
            }
        } catch (UsuarioException nm) {
            JOptionPane.showMessageDialog(this, nm.getMessage(), "Mensaje", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString(), "Mensaje", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonCamareroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBiblioteca;
    private javax.swing.JButton jButtonBibliotecario;
    private javax.swing.JButton jButtonCafeteria;
    private javax.swing.JButton jButtonCamarero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelApellidos;
    private javax.swing.JLabel jLabelBibliotecario;
    private javax.swing.JLabel jLabelCafeteria;
    private javax.swing.JLabel jLabelCamarero;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPrestamos;
    // End of variables declaration//GEN-END:variables
}
