package ventanas;

import BuilderMenu.DirectorBuilder;
import BuilderMenu.MenuBuilder;
import BuilderMenu.MenuLibreBuilder;
import FactProductosCafeteria.Bebida;
import FactProductosCafeteria.Comida;
import FactProductosCafeteria.FactoriaProductoCafeteria;
import FactProductosCafeteria.Menu;
import FactProductosCafeteria.Postre;
import FactProductosCafeteria.ProductoCafeteria;
import bibliotecacafeteria.Cafeteria;
import PersonalUniversidad.PersonalUniversidad;
import SingletonProxyServidor.SingletonProxyServidor;
import SingletonProxyServidor.TipoArchivo;
import java.awt.Color;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class VentanaAltaProductoCafeteria extends javax.swing.JFrame {

    private VentanaCamarero padre;

    private PersonalUniversidad usuario;
    
    /**
     * Creates new form VentanaAltaProductoCafeteria
     */
    public VentanaAltaProductoCafeteria(VentanaCamarero ventana, PersonalUniversidad usuario) throws IOException, ClassNotFoundException  {
        initComponents();
        padre = ventana;
        padre.setVisible(false);
        this.setVisible(true);
        this.getContentPane().setBackground(Color.orange);
        this.usuario = usuario;
        jLabelNombre.setText(usuario.getNombre());
        jLabelApellidos.setText(usuario.getApellidos());
        
        actualizarComboBoxMenu();
        
    }
    
    
    private void actualizarComboBoxMenu() throws IOException, ClassNotFoundException{
        try {
            //Obtenemos todas las comidas y bebidas disponibles de la cafeteria
            //en la que está el camarero que entra a esta ventana
            String nombre_cafeteria = usuario.getRolCamarero().getNombre_cafeteria();
            Cafeteria cafeteria = (Cafeteria) SingletonProxyServidor.getInstancia().cargar_archivo(TipoArchivo.CAFETERIA, nombre_cafeteria);
            ArrayList<ProductoCafeteria> listaProductosCafeteria = cafeteria.getProductos();
            jComboBoxPrimerPlato.removeAllItems();
            jComboBoxSegundoPlato.removeAllItems();
            jComboBoxPostre.removeAllItems();
            jComboBoxBebida.removeAllItems();
            for (ProductoCafeteria entry : listaProductosCafeteria) {
                System.out.println("clave=" + entry.getIdentificador() + ", valor=" + entry.getNombre());
                if(entry instanceof Comida){
                    jComboBoxPrimerPlato.addItem(entry.getIdentificador());
                    jComboBoxSegundoPlato.addItem(entry.getIdentificador());
                }else if(entry instanceof Postre){                  
                    jComboBoxPostre.addItem(entry.getIdentificador());
                }else if(entry instanceof Bebida){
                    jComboBoxBebida.addItem(entry.getIdentificador());
                }else{
                    //Probablemente sea un Menu, pero no utilizamos en la creación.
                    //Es decir, la creación de nuevo menús no se basa en menús
                    //ya existentes, sino en Comidas y Bebidas  ya existentes.
                }
            }
        }catch(ArrayIndexOutOfBoundsException e){
            System.out.println("\nFue del dominio del array: " + e.toString());
            JOptionPane.showMessageDialog(null,"\nFue del dominio del array: " + e.toString(),"Fallo",JOptionPane.ERROR_MESSAGE);

        }catch(NumberFormatException e){
            System.out.println("\nError en la conversión: " + e.toString());
            JOptionPane.showMessageDialog(null,"\nError en el formato del numero: " ,"Fallo",JOptionPane.ERROR_MESSAGE);

        }catch(NullPointerException e){
            System.out.println("\nVariable no definida: " + e.toString());
            JOptionPane.showMessageDialog(null,"\nVariable no definida: " + e.toString(),"Fallo",JOptionPane.ERROR_MESSAGE);

        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"\nSe ha podrucido un error: " + e.toString(),"Fallo",JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelPrecio = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelApellidos = new javax.swing.JLabel();
        jTextFieldPrecio = new javax.swing.JTextField();
        jButtonCrearProducto = new javax.swing.JButton();
        jComboBoxTipoProducto = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxPrimerPlato = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxSegundoPlato = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxPostre = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxBebida = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SISTEMA CAFETERIA Y BIBLIOTECA");
        setPreferredSize(new java.awt.Dimension(551, 455));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jLabel1.setText("Tipo de Producto");

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jLabel2.setText("Nombre");

        jLabelPrecio.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jLabelPrecio.setText("Precio");

        jLabelId.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jLabelId.setText("ID");

        jLabel3.setText("Nombre");

        jLabel4.setText("Apellidos");

        jLabelNombre.setText("jLabel5");

        jLabelApellidos.setText("jLabel5");

        jButtonCrearProducto.setBackground(new java.awt.Color(0, 0, 0));
        jButtonCrearProducto.setForeground(new java.awt.Color(255, 255, 0));
        jButtonCrearProducto.setText("Crear producto");
        jButtonCrearProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearProductoActionPerformed(evt);
            }
        });

        jComboBoxTipoProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Comida", "Bebida", "Menu", "Postre" }));
        jComboBoxTipoProducto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxTipoProductoItemStateChanged(evt);
            }
        });
        jComboBoxTipoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoProductoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jLabel6.setText("Menu");
        jLabel6.setEnabled(false);

        jComboBoxPrimerPlato.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jLabel7.setText("Primer plato");

        jLabel8.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jLabel8.setText("Segundo plato");

        jComboBoxSegundoPlato.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jLabel9.setText("Postre");

        jComboBoxPostre.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jLabel10.setText("Bebida");

        jComboBoxBebida.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(402, 402, 402)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelNombre))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(402, 402, 402)
                        .addComponent(jLabel4)
                        .addGap(10, 10, 10)
                        .addComponent(jLabelApellidos))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)
                        .addGap(32, 32, 32)
                        .addComponent(jComboBoxTipoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jButtonCrearProducto))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(164, 164, 164)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(40, 40, 40)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jComboBoxPrimerPlato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBoxSegundoPlato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(100, 100, 100)
                                        .addComponent(jComboBoxPostre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(90, 90, 90)
                                        .addComponent(jComboBoxBebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabelNombre))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabelApellidos))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxTipoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jComboBoxPrimerPlato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxSegundoPlato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jComboBoxPostre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPrecio)
                            .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(jLabelId))
                    .addComponent(jComboBoxBebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(jButtonCrearProducto))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCrearProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearProductoActionPerformed
        try {
            String nombre_cafeteria = usuario.getRolCamarero().getNombre_cafeteria();
            Cafeteria cafeteria = (Cafeteria) SingletonProxyServidor.getInstancia().cargar_archivo(TipoArchivo.CAFETERIA, nombre_cafeteria);
            if(jComboBoxTipoProducto.getSelectedIndex() == 2){

                String nombre = jTextFieldNombre.getText();
                float precio = Float.valueOf(jTextFieldPrecio.getText());
                String id = jTextFieldId.getText();

                MenuBuilder menuBuilder = new MenuLibreBuilder();  
                menuBuilder.crearNuevoMenu(nombre, precio, id, cafeteria);

                DirectorBuilder directorBuilder = new DirectorBuilder();
                directorBuilder.setMenuBuilder(menuBuilder);

                //Obtenemos los ProductosCafeteria de los jComboBox
                ArrayList<ProductoCafeteria> listaProductosCafeteria = cafeteria.getProductos();

                Comida primerPlato = null;
                Comida segundoPlato = null;
                Postre postre = null;
                Bebida bebida = null;
                for (ProductoCafeteria entry : listaProductosCafeteria) {
                    if(entry instanceof Comida){
                        if(entry.getIdentificador().equals(jComboBoxPrimerPlato.getSelectedItem())){
                            primerPlato = (Comida) entry;
                        }
                        if(entry.getIdentificador().equals(jComboBoxSegundoPlato.getSelectedItem())){
                            segundoPlato = (Comida) entry;
                        }
                    }else if(entry instanceof Postre){
                        if(entry.getIdentificador().equals(jComboBoxPostre.getSelectedItem())){
                            postre = (Postre) entry;
                        }
                    }else if(entry instanceof Bebida){
                        if(entry.getIdentificador().equals(jComboBoxBebida.getSelectedItem())){
                            bebida = (Bebida) entry;
                        }
                    }else{
                        //Probablemente sea un Menu, pero no utilizamos en la creación.
                        //Es decir, la creación de nuevo menús no se basa en menús
                        //ya existentes, sino en Comidas y Bebidas  ya existentes.
                    }
                }            

                directorBuilder.crearMenu(primerPlato, segundoPlato, postre, bebida);
                Menu menu2 = directorBuilder.getMenu();
                cafeteria.añadirProducto(menu2);

                
                SingletonProxyServidor singletonProxyServidor = SingletonProxyServidor.getInstancia();
                try {
                    //Guardar la nueva Cafeteria en su carpeta.
                    singletonProxyServidor.guardar_archivo(cafeteria);
                } catch (IOException ex) {
                    Logger.getLogger(VentanaAltaProductoCafeteria.class.getName()).log(Level.SEVERE, null, ex);
                } 
            }else{
                String nombre = jTextFieldNombre.getText();
                float precio = Float.valueOf(jTextFieldPrecio.getText());
                String id = jTextFieldId.getText();
                int tipoProductoString = jComboBoxTipoProducto.getSelectedIndex();
                System.out.println(tipoProductoString);

                //Recordemos que la factoria ya introduce el Producto en el objeto Cafeteria correspondiente.
                ProductoCafeteria comida = new FactoriaProductoCafeteria().getProductoCafeteria(tipoProductoString, nombre, precio, id, cafeteria);

                SingletonProxyServidor singletonProxyServidor = SingletonProxyServidor.getInstancia();
                try {
                    //Más que guardar comidas y cafeterias, lo importante es guardar
                    //a la persona, puesto que en ella está la nueva Cafeteria.
                    singletonProxyServidor.guardar_archivo(cafeteria);
                } catch (IOException ex) {
                    Logger.getLogger(VentanaAltaProductoCafeteria.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
            actualizarComboBoxMenu();
            JOptionPane.showMessageDialog(this,"\nProducto creado! " ,"Info",JOptionPane.INFORMATION_MESSAGE);     
        } catch (IOException | ClassNotFoundException ex) {
                Logger.getLogger(VentanaAltaProductoCafeteria.class.getName()).log(Level.SEVERE, null, ex);
        }  
    }//GEN-LAST:event_jButtonCrearProductoActionPerformed

    private void jComboBoxTipoProductoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxTipoProductoItemStateChanged
        if(jComboBoxTipoProducto.getSelectedIndex() == 2){
           jComboBoxPrimerPlato.setEnabled(true);
           jComboBoxSegundoPlato.setEnabled(true);
           jComboBoxPostre.setEnabled(true);
           jComboBoxBebida.setEnabled(true);
        }else{
           jComboBoxPrimerPlato.setEnabled(false);
           jComboBoxSegundoPlato.setEnabled(false);
           jComboBoxPostre.setEnabled(false);
           jComboBoxBebida.setEnabled(false);
        }
    }//GEN-LAST:event_jComboBoxTipoProductoItemStateChanged

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        padre.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void jComboBoxTipoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipoProductoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCrearProducto;
    private javax.swing.JComboBox<String> jComboBoxBebida;
    private javax.swing.JComboBox<String> jComboBoxPostre;
    private javax.swing.JComboBox<String> jComboBoxPrimerPlato;
    private javax.swing.JComboBox<String> jComboBoxSegundoPlato;
    private javax.swing.JComboBox<String> jComboBoxTipoProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelApellidos;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPrecio;
    // End of variables declaration//GEN-END:variables
}
